const ProductcardData = [
    {
      id: 1,
      categoryId : 1,
      category: "Fresh Vegetables",
      name: "Potato",
      weight: "1kg",
      offer: "10% off",
      oldPrice: "$17",
      newPrice: "$15",
      time: "sourced at 5AM",
      img: "https://m.media-amazon.com/images/I/313dtY-LOEL._AC_UF1000,1000_QL80_.jpg",
    },
    {
      id: 2,
      categoryId : 1,
      category: "Fresh Vegetables",
      name: "Onion",
      weight: "1kg",
      offer: "21% off",
      oldPrice: "$41",
      newPrice: "$32",
      time: "sourced at 5AM",
      img: "https://m.media-amazon.com/images/I/81p4sgrCfzL._AC_UF1000,1000_QL80_.jpg",
    },
    {
      id: 3,
      categoryId : 1,
      category: "Fresh Vegetables",
      name: "Carrot",
      weight: "500g",
      offer: "10% off",
      oldPrice: "$19",
      newPrice: "$17",
      time: "sourced at 5AM",
      img: "https://seed2plant.in/cdn/shop/products/carrotseeds_800x.jpg?v=1604032858",
    },
    {
      id: 4,
      categoryId : 1,
      category: "Fresh Vegetables",
      name: "Tomato",
      weight: "500g",
      offer: "21% off",
      oldPrice: "$19",
      newPrice: "$15",
      time: "sourced at 5AM",
      img: "https://upload.wikimedia.org/wikipedia/commons/8/89/Tomato_je.jpg",
    },
    {
      id: 5,
      categoryId : 2,
      category: "Fresh Fruits",
      name: "Apple",
      weight: "500g",
      offer: "21% off",
      oldPrice: "$19",
      newPrice: "$15",
      time: "sourced at 5AM",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS12-ZKcoBDFxln0RGUo5Dd2gRGVleff35T0VzJ1JeERFV_xPDcjt-QjE7skXYvvuPWRU0&usqp=CAU",
    },
    {
      id: 6,
      categoryId : 2,
      category: "Fresh Fruits",
      name: "Graphes",
      weight: "500g",
      offer: "21% off",
      oldPrice: "$19",
      newPrice: "$15",
      time: "sourced at 5AM",
      img: "https://m.media-amazon.com/images/I/71XJo0XZq4L._AC_UF894,1000_QL80_.jpg",
    },
    {
      id: 7,
      categoryId : 2,
      category: "Fresh Fruits",
      name: "Banana",
      weight: "500g",
      offer: "21% off",
      oldPrice: "$19",
      newPrice: "$15",
      time: "sourced at 5AM",
      img: "https://www.bobtailfruit.co.uk/pub/media/mageplaza/blog/post/4/2/42e9as7nataai4a6jcufwg.jpeg",
    },
  
    {
      id: 8,
      categoryId : 2,
      category: "Fresh Fruits",
      name: "Orange",
      weight: "500g",
      offer: "21% off",
      oldPrice: "$19",
      newPrice: "$15",
      time: "sourced at 5AM",
      img: "https://5.imimg.com/data5/MU/LW/MY-12647059/fresh-orange-500x500.jpg",
    },
    {
      id: 9,
      categoryId : 3,
      category: "Seasonal",
      name: "Mango",
      weight: "500g",
      offer: "21% off",
      oldPrice: "$19",
      newPrice: "$15",
      time: "sourced at 5AM",
      img: "https://m.media-amazon.com/images/I/31cXlUcvRVL._AC_UF1000,1000_QL80_.jpg",
    },
    {
      id: 10,
      categoryId : 3,
      category: "Seasonal",
      name: "Pears   ",
      weight: "500g",
      offer: "21% off",
      oldPrice: "$19",
      newPrice: "$15",
      time: "sourced at 5AM",
      img: "https://www.bigbasket.com/media/uploads/p/l/40174618_4-fresho-pear-beauty.jpg",
    },
    {
      id: 11,
      categoryId : 3,
      category: "Seasonal",
      name: "Avacado",
      weight: "500g",
      offer: "21% off",
      oldPrice: "$19",
      newPrice: "$15",
      time: "sourced at 5AM",
      img: "https://www.bigbasket.com/media/uploads/p/l/10000312_19-fresho-avocado.jpg",
    },
  ];

  export default ProductcardData;